name: CI
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3.2.2

      - name: Upload Android SDK as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-sdk-bundle
          # We list the specific subdirectories relative to the SDK root
          path: |
            ${{ env.ANDROID_HOME }}/add-ons
            ${{ env.ANDROID_HOME }}/build-tools
            ${{ env.ANDROID_HOME }}/licenses
            ${{ env.ANDROID_HOME }}/platform-tools
            ${{ env.ANDROID_HOME }}/platforms
            ${{ env.ANDROID_HOME }}/sources
          retention-days: 5
