name: CI

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3.2.2

      - name: Upload Android SDK as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-sdk-bundle
          # We use the environment variable to locate the path dynamically
          path: ${{ env.ANDROID_HOME }}
          # Optional: SDKs are large, so you might want to set a short retention
          retention-days: 5
